# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3541b61dce7bf0a7c25fb933279c3ab3cc6d407058ff15cfa7a20105a215d76166435fbe4ada4733cb0097fc53792585a8e5393046ba18ebb37654165408770

test:
  secret_key_base: 7466eee13c5f4368a1c64f7fed8f25934c255e747432346923fb18c275cf2f9c619f54c99997a4daa8d22f690c1571f99a7318472cc67e6e82e828a7f61d5a28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
